export const ACCOUNT_MAPPING_RULES = {
    "Current Asset": {
        "control_code": "AST",
        "control_name": "Assets",
        "category": "ASSET",
        "fs": "BALANCE_SHEET",
        "normal_balance": "DEBIT",
    },
    "Non-current Asset": {
        "control_code": "AST",
        "control_name": "Assets",
        "category": "ASSET",
        "fs": "BALANCE_SHEET",
        "normal_balance": "DEBIT",
    },
    "Long Term Liabilities": {
        "control_code": "LIA",
        "control_name": "Liabilities",
        "category": "LIABILITY",
        "fs": "BALANCE_SHEET",
        "normal_balance": "CREDIT",
    },
    "Short Term Liabilities": {
        "control_code": "LIA",
        "control_name": "Liabilities",
        "category": "LIABILITY",
        "fs": "BALANCE_SHEET",
        "normal_balance": "CREDIT",
    },
    "Owner's Equities": {
        "control_code": "EQT",
        "control_name": "Equity",
        "category": "EQUITY",
        "fs": "BALANCE_SHEET",
        "normal_balance": "CREDIT",
    },
    "Operating Income": {
        "control_code": "INC",
        "control_name": "Income",
        "category": "INCOME",
        "fs": "PROFIT_LOSS",
        "normal_balance": "CREDIT",
    },
    "Non-Operating Income": {
        "control_code": "INC",
        "control_name": "Income",
        "category": "INCOME",
        "fs": "PROFIT_LOSS",
        "normal_balance": "CREDIT",
    },
    "Operating Expense": {
        "control_code": "EXP",
        "control_name": "Expense",
        "category": "EXPENSE",
        "fs": "PROFIT_LOSS",
        "normal_balance": "DEBIT",
    },
    "Non-Operating Expense": {
        "control_code": "EXP",
        "control_name": "Expense",
        "category": "EXPENSE",
        "fs": "PROFIT_LOSS",
        "normal_balance": "DEBIT",
    },
    "Cost of Good Sold": {
        "control_code": "COGS",
        "control_name": "Cost of Goods Sold",
        "category": "EXPENSE",
        "fs": "PROFIT_LOSS",
        "normal_balance": "DEBIT",
    },
}
